#!/bin/bash

wget -O /root/web_transfer01.py https://github.com/dgou45/fhs-install-v2ray/blob/ssr/web_transfer01.py
wget -O /root/tcprelay01.py https://github.com/dgou45/fhs-install-v2ray/blob/ssr/tcprelay01.py

wget -O /root/web_transfer02.py https://github.com/dgou45/fhs-install-v2ray/blob/ssr/web_transfer02.py
wget -O /root/tcprelay02.py https://github.com/dgou45/fhs-install-v2ray/blob/ssr/tcprelay02.py

web_transfer01="/root/web_transfer01.py"
tcprelay01="/root/tcprelay01.py"

web_transfer02="/root/web_transfer02.py"
tcprelay02="/root/tcprelay02.py"

web_transfer="/root/shadowsocks-mod/web_transfer.py"
tcprelay="/root/shadowsocks-mod/shadowsocks/tcprelay.py"

# 比较 web_transfer 是否相同
if cmp -s "$web_transfer01" "$web_transfer"; then
    echo "与 web_transfer01 相同，开启替换"
    commandA
elif cmp -s "$web_transfer02" "$web_transfer"; then
    echo "与 web_transfer02 相同，开启替换"
    commandA
else
    echo "文件不同"
    commandB
fi

# 比较 tcprelay 是否相同
if cmp -s "$tcprelay01" "$tcprelay"; then
    echo "与 tcprelay01 相同，开启替换"
    commandA
elif cmp -s "$tcprelay02" "$tcprelay"; then
    echo "与 tcprelay02 相同，开启替换"
    commandA
else
    echo "文件不同"
    commandB
fi
